artifacts:
  specs: org.scala-tools.testing:specs_2.8.0.RC5:jar:1.6.5-SNAPSHOT
  scalacheck: org.scala-tools.testing:scalacheck_2.8.0.RC5:jar:1.8-SNAPSHOT
  mockito: org.mockito:mockito-all:jar:1.8.4
  cglib: cglib:cglib:jar:2.1_3
  asm: asm:asm:jar:1.5.3
  objenesis: org.objenesis:objenesis:jar:1.1
  hamcrest: org.hamcrest:hamcrest-all:jar:1.1
